- name: install some additional soft
  apt:
    package: ['adduser', 'libfontconfig']

- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.4.4_amd64.deb
    dest: /opt/grafana_6.4.4_amd64.deb

- name: install
  apt:
    deb: /opt/grafana_6.4.4_amd64.deb

- name: start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
