---
#agent  = infra01 = bind slave  = 192.168.56.101
#server = infra02 = bind master = 192.168.56.102
- name: node_exporter
  hosts: linux
  become: yes
  roles:
    - bind
    - node_exporter

- name: MySQL VM2
  hosts: server
  become: yes
  roles:
    - mysql
    - prometheus
    - grafana
    - mysql_exporter

- name: Wordpress VM1
  hosts: agent
  become: yes
  roles:
    - wordpress
