- name: add user to var
  command: "whoami"
  register: user
   
- name: disable sudo pass
  become: yes
  copy:
    dest: /etc/sudoers.d/user
    content: "{{ user.stdout }}      ALL = NOPASSWD: ALL"

- name: create config file for enp0s8
  become: yes
  blockinfile:
    create: yes
    path: /etc/netplan/55-enp0s8.yaml
    block: |
      network:
         ethernets:
             enp0s8:
                 dhcp4: true
         version: 2
  notify:
    - netplan apply
   
- name: add public ssh key
  become: yes
  copy:
    src: /home/riderofthesky/.ssh/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
  
- name: change rights of the ~/.ssh
  become: yes
  file:
    path: ~/.ssh
    mode: '1700'

- name: add public ssh key to user
  become: yes
  copy:
    src: /home/riderofthesky/.ssh/id_rsa.pub
    dest: /home/{{ user.stdout }}/.ssh/id_rsa.pub
  
- name: change rights of the user directory
  become: yes
  file:
    path: /home/{{user.stdout}}/.ssh
    mode: '1700' 

- name: copy public key
  become: yes
  authorized_key:
    user: "{{ user.stdout }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
