- name: install some additional soft
  apt:
    package: ['docker.io', 'python', 'python-pip']

- name: install Docker py module
  pip:
    name: docker

- name: create grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    
- name: start container with grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    published_ports:
      - "3000:3000"
