- name: install some additional soft
  apt:
    package: ['adduser', 'libfontconfig']

- name: check if exists
  stat:
    path: /opt/grafana_6.4.4_amd64.deb
  register: abc

- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.4.4_amd64.deb
    dest: /opt/grafana_6.4.4_amd64.deb
  when: abc.stat.exists == False

- name: install
  apt:
    deb: /opt/grafana_6.4.4_amd64.deb

- name: start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

#- name: Network Setup
#  hosts: all
#  become: yes
#  tasks:
#- name: systemd-resolved
#  service:
#    name: systemd-resolved
#    state: stopped
#    enabled: no
  

#- name: Setup dns (bind9)
#  hosts: dns
#  become: yes
#  tasks:
