- name: install docker
  apt:
    name: ['docker.io', 'python', 'python-pip']

- name: install Docker py module
  pip:
    name: docker

- name: create wp container
  docker_container:
    name: wp
    image: wordpress

- name: stop container
  docker_container: 
    name: wp
    state: stopped

- name: command
  shell: docker run -e WORDPRESS_DB_HOST=192.168.56.102:3306 -e WORDPRESS_DB_USER={{username}} -e WORDPRESS_DB_PASSWORD={{password}} -p8080:80 -d wordpress
