- name: Specify MySQL root pass
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password'
    value: '{{ root_password  | quote }}'
    vtype: 'password'

- name: Confirm MySQL root pass
  debconf:
    name: 'mysql-server'
    question: 'mysql-server/root_password_again'
    value: '{{ root_password  | quote }}'
    vtype: 'password'

- name: Install MySQL python module
  apt: 
    name: python-pymysql
    state: latest 
    force_apt_get: yes

- name: install all needed stuff
  apt:
    name: ['python', 'python-pip', 'python-mysqldb']
    state: latest

- name: Install MySQL server
  apt: 
    name: mysql-server 
    state: latest 
    force_apt_get: yes

- name: update .my.cnf
  template:
    src: .my.cnf
    dest: ~/.my.cnf

- name: create MySQL DB
  mysql_db:
    name: "{{ db_name }}"
    login_user: "root"
    login_password: "{{ root_password }}"
    state: present

- name: Create MySQL user
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: 'wordpress.*:ALL'
    host: "%"

- name: allow remote access to MySQL db
  template:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
