- name: install all needed stuff
  apt:
    name: ['python', 'python-pip', 'python-pymysql']
    state: latest

- name: Install MySQL
  apt: 
    name: mysql-server 
    state: latest 
    force_apt_get: yes

- name: create MySQL DB
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create MySQL user
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: 'wordpress.*:ALL,GRANT'

- name: Create MySQL user for remote access
  mysql_user:
    name: "{{ username }}"
    password: "{{ password }}"
    priv: 'wordpress.*:ALL,GRANT'
    host: "%"

- name: allow remote access to MySQL db
  replace: 
    path: /etc/mysql/mysql.conf.d/mysqld.cnf 
    regexp: 'bind-address		= 127.0.0.1'
    replace: 'bind-address		= 0.0.0.0'
