---
#- name: Network Setup
#  hosts: all
#  become: yes
#  tasks:
#- name: systemd-resolved
#  service:
#    name: systemd-resolved
#    state: stopped
#    enabled: no
  

#- name: Setup dns (bind9)
#  hosts: dns
#  become: yes
#  tasks:
- name: dns packeges
  apt:
    name: bind9
    update_cache: yes
    state: present
    force_apt_get: yes 

- name: config bind9 named.conf.options
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - restart bind
    - check conf     

- name: config bind9 named.conf.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - restart bind
    - check conf
    
- name: hash
  copy:
    content: "{{dns_records|hash}}"
    dest: /etc/bind/db.riderly.hash
  when: dns_role == "master"
  notify:
    - timestamp
    - config db
    - reload DB

- name: check if exists
  stat:
    path: /opt/go1.13.3.linux-amd64.tar.gz
  register: abc

- name: download GO
  get_url:
    url: https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go1.13.3.linux-amd64.tar.gz
  when: abc.stat.exists == False

- name: folder
  file:
    path: /opt/go
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go
    remote_src: yes

- name: create a symbolic link
  file:
    src: /opt/go/go/bin/go
    dest: /usr/local/bin/go
    state: link

- name: check that the file exists
  stat:
    path: /root/go/src/github.com/digitalocean/bind_exporter/bind_exporter.go
  register: stat_result

- name: go get
  shell: "go get github.com/digitalocean/bind_exporter"
  when: stat_result.stat.exists == False

- name: copy binary
  copy:
    src: /root/go/bin/bind_exporter
    dest: /usr/local/bin/bind_exporter
    mode: u=rwx,g=rx,o=rx
    remote_src: yes

- name: make a service
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service

- name: start bind service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - bind9
    - bind_exporter
